# Generated by Django 5.2.14 on 2026-05-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('done', 'Done')], max_length=20),
        ),
    ]
